- hosts: 172.31.7.237
  become: true
  vars:
    - tomcat-url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.58/bin/apache-tomcat-9.0.58.tar.gz
    - tomcat-package: apache-tomcat-9.0.58.tar.gz
    - java-version: java-1.8.0-openjdk
  tasks:
    - name: Install Java
      yum:
        name: "{{ java-version }}"
        state: present
    - name: add tomcatuser
      user:
        name: tomcat
        shell: /sbin/nologin
    - name: get_installer
      get_url:
        url: "{{ tomcat-url }}"
        dest: /tmp/
    - name: copy
      copy:
        src: /tmp/{{ tomcat-package }}
        dest: /usr/local/
        remote_src: yes
    - name: install
      unarchive:
        src: /usr/local/{{ tomcat-package }}
        dest: /usr/local
        remote_src: yes
    - name: Change file ownership, group and permissions
      file:
        path: /usr/local/{{ tomcat-package }}
        owner: tomcat
        group: tomcat
        recurse: yes
        state: directory
    - name: make tomcat symbolic
      file:
        src: /usr/local/{{ tomcat-package }}
        dest: /usr/local/tomcat9
        owner: tomcat
        group: tomcat
        state: link
    - name: make tomcat.service
      file:
        path: /etc/systemd/system/tomcat.service
        state:  touch
    - name: edit tomcat.service
      blockinfile:
        dest: /etc/systemd/system/tomcat.service
        insertafter:
        block: |
          [Unit]
          Description = Apache Tomcat 9
          After = syslog.target network.target
          [Service]
          User = tomcat
          Group = tomcat
          Type = oneshot
          PIDFile =/usr/local/{{ tomcat-package }}/tomcat.pid
          RemainAfterExit = yes
          ExecStart =/usr/local/{{ tomcat-package }}/bin/startup.sh
          ExecStop =/usr/local/{{ tomcat-package }}/bin/shutdown.sh
          ExecReStart =/usr/local/{{ tomcat-package }}/bin/shutdown.sh;/usr/local/{{ tomcat-package }}/bin/startup.sh
          [Install]
          WantedBy = multi-user.target
    - name: chmod 755 tomcat.service
      file:
        path: /etc/systemd/system/tomcat.service
        mode:  0755
    - name: start tomcat
      systemd:
        name: tomcat.service
        state: started
        daemon_reload: yes
        enabled: yes
